# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdf_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pdf_service.proto\x12\npdfservice\"T\n\x10UploadPDFRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x15\n\rdocument_type\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"$\n\x11UploadPDFResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07\x66ilters\x18\x02 \x01(\t\"8\n\x0eSearchResponse\x12\x15\n\rsearch_result\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x10SummarizeRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x66ilters\x18\x03 \x01(\t\"5\n\x11SummarizeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe3\x01\n\nPDFService\x12J\n\tUploadPDF\x12\x1c.pdfservice.UploadPDFRequest\x1a\x1d.pdfservice.UploadPDFResponse(\x01\x12?\n\x06Search\x12\x19.pdfservice.SearchRequest\x1a\x1a.pdfservice.SearchResponse\x12H\n\tSummarize\x12\x1c.pdfservice.SummarizeRequest\x1a\x1d.pdfservice.SummarizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdf_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADPDFREQUEST']._serialized_start=33
  _globals['_UPLOADPDFREQUEST']._serialized_end=117
  _globals['_UPLOADPDFRESPONSE']._serialized_start=119
  _globals['_UPLOADPDFRESPONSE']._serialized_end=155
  _globals['_SEARCHREQUEST']._serialized_start=157
  _globals['_SEARCHREQUEST']._serialized_end=204
  _globals['_SEARCHRESPONSE']._serialized_start=206
  _globals['_SEARCHRESPONSE']._serialized_end=262
  _globals['_SUMMARIZEREQUEST']._serialized_start=264
  _globals['_SUMMARIZEREQUEST']._serialized_end=331
  _globals['_SUMMARIZERESPONSE']._serialized_start=333
  _globals['_SUMMARIZERESPONSE']._serialized_end=386
  _globals['_PDFSERVICE']._serialized_start=389
  _globals['_PDFSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
