# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14search_service.proto\x12\x08\x64ocument\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\'\n\x0eSearchResponse\x12\x15\n\rsearch_result\x18\x01 \x01(\t\"\x8c\x01\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x32\n\x08metadata\x18\x03 \x03(\x0b\x32 .document.Document.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32W\n\rSearchService\x12\x46\n\x0fSearchDocuments\x12\x17.document.SearchRequest\x1a\x18.document.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=34
  _globals['_SEARCHREQUEST']._serialized_end=64
  _globals['_SEARCHRESPONSE']._serialized_start=66
  _globals['_SEARCHRESPONSE']._serialized_end=105
  _globals['_DOCUMENT']._serialized_start=108
  _globals['_DOCUMENT']._serialized_end=248
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=201
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=248
  _globals['_SEARCHSERVICE']._serialized_start=250
  _globals['_SEARCHSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
