name: Example Workflow with Multiple Secrets
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Use secrets
        run: |
          echo "NPM_TOKEN: ${{ secrets.NPM_TOKEN }}"
          echo "SUPERSECRET: ${{ secrets.SUPERSECRET }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SUPERSECRET: ${{ secrets.SUPERSECRET }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
