name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file dynamically
      run: |
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV
        echo "QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}" >> $GITHUB_ENV
        echo "QDRANT_URL=${{ secrets.QDRANT_URL }}" >> $GITHUB_ENV
        echo "REDIS_DB=${{ secrets.REDIS_DB }}" >> $GITHUB_ENV
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
      env:
        GITHUB_ENV: /github/workflow/env

    - name: Print environment variables
      run: |
        echo "GROQ_API_KEY: $GROQ_API_KEY"
        echo "QDRANT_API_KEY: $QDRANT_API_KEY"
        echo "QDRANT_URL: $QDRANT_URL"
        echo "REDIS_DB: $REDIS_DB"
        echo "REDIS_HOST: $REDIS_HOST"
        echo "REDIS_PASSWORD: $REDIS_PASSWORD"
        echo "REDIS_PORT: $REDIS_PORT"

    - name: Run tests
      run: pytest
