name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file dynamically
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        QDRANT_URL: ${{ secrets.QDRANT_URL }}
        REDIS_DB: ${{ secrets.REDIS_DB }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
      run: |
        echo "GROQ_API_KEY=${GROQ_API_KEY}" > .env
        echo "QDRANT_API_KEY=${QDRANT_API_KEY}" >> .env
        echo "QDRANT_URL=${QDRANT_URL}" >> .env
        echo "REDIS_DB=${REDIS_DB}" >> .env
        echo "REDIS_HOST=${REDIS_HOST}" >> .env
        echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env
        echo "REDIS_PORT=${REDIS_PORT}" >> .env

    - name: Cache .env file
      uses: actions/cache@v3
      with:
        path: .env
        key: env-cache-${{ github.sha }}

    - name: Debug environment variables
      run: |
        cat .env

    - name: Run tests
      run: |
        source .env
        pytest