name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      QDRANT_URL: ${{ secrets.QDRANT_URL }}
      REDIS_DB: ${{ secrets.REDIS_DB }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        - name: Print environment variables
        run: |
          echo "GROQ_API_KEY=$GROQ_API_KEY"
          echo "QDRANT_API_KEY=$QDRANT_API_KEY"
          echo "QDRANT_URL=$QDRANT_URL"
          echo "REDIS_DB=$REDIS_DB"
          echo "REDIS_HOST=$REDIS_HOST"
          echo "REDIS_PASSWORD=$REDIS_PASSWORD"
          echo "REDIS_PORT=$REDIS_PORT"

    # - name: Run tests
    #   run: pytest

